dist: trusty
sudo: required
language: c
env:
  global:
   - secure: "Tykqgw/+g2A1i7qXPF77lI5jWmU3j1Agox29rm8ZJpCE8kIoa9hjQ7Ev7QlrlipiScX5nmS96ANe2R9dLWQc+237L8blwD5R5hSsr8thaDQML1M4HjzFDhuVuW1+5ZgwLrXANgL7Q7ZermBmRcVF1uq8t+dGwVI3xC7CEaw1rJW4LL4QEdPr/tq7TE0xJyuemt1d0ceghPtuqSbZiYXuk/svrSxbAz0wd3m5ptaWX6KFOde/gVaXctFbToOk9De9sNDJnX4R9yoENf2ScFMRzCN0GkOnJnwFHS8yKLUc741SzU3jG2FQ+CFycSI403kIl3ja3KbTl3WQIiFeJxJbjIO1iVMsOmATN/TEEjKYgFJZdCrGVCnXmbJT5pACTDTA2f41bkiJJX/3pjNFpNmt1gctaJ2FY1AlUD6AA5BCWzeomun8OBzm2jVe7yk7x36c6aGYeG+Ib+Qz+uxNZqIYS0iZ9o3t/HO29PGRW1ofIj+9z5kYr70gTP0EeQvUFcjBpV9V1Pwa4CT8b4KiCpkMuBTs0or6MXK0WyAJ7JtOVVPmfnmBozrXocnqyojdljVaycaUOyWwXabW4NL5A4juQWIsHSfuWJ5fChd8tkGBaXW5Fsf7rqcp+lv45r2qz80TvoXxY5/VsgzEr4al9RrSsfRjFy9tTRum0+6+mm2SIeg="
matrix:
  include:
    os: linux
    compiler: clang
    addons:
      coverity_scan:
        project:
          name: "bloodstalker/mutator"
          description: "Build submitted via Travis CI"
        notification_email: thabogre@gmail.com
        build_command_prepend: "cov-configure --comptype clangcxx --compiler clang-5.0"
        build_command:   "make CC=gcc"
        branch_pattern: master

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
        #- pip install --user cpp-coveralls

before_script: 
#- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#- sudo add-apt-repository ppa:fkrull/deadsnakes -y
#- sudo apt-get update -y
#- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get install luarocks -y
  - luarocks install ansicolors --local
  - git submodule init
  - git submodule update

script: 
  - make -j2

after_failure:
  - find . -maxdepth 1 -name "core*"

after_success:
  - gcc -v
  - gcov -v
  - gcc -v
    #- coveralls --exclude ./json --exclude ./tinyxml2 --exclude-pattern 'clang' --exclude-pattern 'llvm'
    #- gcc -E - <<< '#include<stddef.h>'
    #- gcc -E - <<< '#include<assert.h>'
