dist: trusty
sudo: required
language: c
env:
  global:
   - secure: "VAdPa4SeDaJWWzQwz6m1/8xbr4bDcfd+1qlvOi6+dVhSeilWAyoEBaEaQ4pdp6oD+RvPyuNj6I+9h02WnM5Yuo/rlhgav0FgnoJus14dYNZijyM9T2yjQiVKFm6x1VMJv6woDtl3BdKOjCFVLUhucAt2ifxS4so3HkbXpX5QPFT8OtPv4W9nvv5cyCIHQyOfEn3oH/JM/o0NeVybPeHksm97nXTenL8EL5N8UaX9sxqzouOnRLXQhrU9p34/AMYbBBbXY5yfc2BNTJIL+Ek/A7g14RZJkmytC3ac123gPDWTC3qXdsyUtBudCigDdDCioDb2BtJdTnvBqLURowM2G/oceMchlSp8sK+qQGZJX6P8DbvfBnkUCBMqAGVu0RqeMuG2pVYVE4dLreAMDxUAHZ1ZO8xEisCWUVEEfK6mJoiNQmrPbiaM5oQKhn5+JOQt5/nGDXEATxuLjy8FKmDdJ+Dgk/dqs4thp7NmMKBFUWOmE+hHHtzCxXdPawXqhd9Gm4QttXoRpsIeadgX2u43iSvlJgwHbUfeQCPitPNwoe4IidbrXtXdTK16G3YxXSivcNJKR3NSp2C0jjsalbIyDmf+iJA3zZ+87+ypIC+/gJLSjR5XASH3conr+C4jl9aPmQIvck7I/6ul+fQXBwfUktc0G3+2+L3fDYPrUKDyns4="
matrix:
  include:
    os: linux
    compiler: clang
    addons:
      coverity_scan:
        project:
          name: "bloodstalker/mutator"
          description: "Build submitted via Travis CI"
        notification_email: thabogre@gmail.com
        build_command_prepend: "cov-configure --comptype clangcxx --compiler clang-5.0"
        build_command:   "make CC=gcc"
        branch_pattern: master

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
        #- pip install --user cpp-coveralls

before_script: 
#- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#- sudo add-apt-repository ppa:fkrull/deadsnakes -y
#- sudo apt-get update -y
#- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get install luarocks -y
  - luarocks install ansicolors --local
  - git submodule init
  - git submodule update

script: 
  - make -j2

after_failure:
  - find . -maxdepth 1 -name "core*"

after_success:
  - gcc -v
  - gcov -v
  - gcc -v
    #- coveralls --exclude ./json --exclude ./tinyxml2 --exclude-pattern 'clang' --exclude-pattern 'llvm'
    #- gcc -E - <<< '#include<stddef.h>'
    #- gcc -E - <<< '#include<assert.h>'
